# Generated by Django 2.2 on 2020-08-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keranjang', to='barang.Barang')),
            ],
        ),
    ]
